import sys
sys.path.insert(0, '.')
from backend.model.news_classifier import NewsClassifierModel

model = NewsClassifierModel()
model.train_or_load()

# Comprehensive test with diverse, realistic news text
test_cases = [
    # Politics
    ("The president signed a new bill into law after heated debate in congress", "Politics"),
    ("The senator proposed a new law to reform healthcare policy", "Politics"),
    ("The prime minister reshuffled the cabinet after poor approval ratings", "Politics"),
    ("The opposition leader called for a no-confidence vote against the prime minister", "Politics"),
    ("The government announced new sanctions against the rogue regime", "Politics"),
    ("The legislature passed a new tax reform bill", "Politics"),
    ("The mayor announced her candidacy for the upcoming gubernatorial race", "Politics"),
    ("The campaign rally drew thousands of supporters to the stadium", "Politics"),
    ("The diplomat was recalled amid the escalating international crisis", "Politics"),
    ("The ruling party lost its majority in parliament following defections", "Politics"),
    
    # Technology
    ("Apple unveiled a new iPhone with AI features", "Technology"),
    ("The tech company announced a breakthrough in quantum computing", "Technology"),
    ("The new processor delivers 50 percent better performance", "Technology"),
    ("The smartphone manufacturer launches flagship device with foldable display", "Technology"),
    ("The cloud infrastructure provider launches high-speed data center network", "Technology"),
    ("The software update brings new privacy features and security enhancements", "Technology"),
    ("The new laptop features a revolutionary battery that lasts 24 hours", "Technology"),
    ("5G network coverage expanded to rural areas for the first time", "Technology"),
    ("The consumer hardware firm introduces next-generation wireless earbuds", "Technology"),
    ("The chip maker unveils new semiconductor architecture", "Technology"),
    
    # Sports
    ("India wins the final match by five wickets in dramatic last-over thriller", "Sports"),
    ("The football team won the championship after a dramatic penalty shootout", "Sports"),
    ("The tennis star won his third Grand Slam title at Wimbledon", "Sports"),
    ("The Olympic swimmer breaks world record in 200m freestyle event", "Sports"),
    ("The NBA team rallies in the fourth quarter to win the conference final", "Sports"),
    ("The star striker scores hat-trick in football league match", "Sports"),
    ("The baseball club wins the league series after a ninth-inning home run", "Sports"),
    ("The badminton champion claims the international open title", "Sports"),
    ("The Formula One driver takes pole position at the Grand Prix circuit", "Sports"),
    ("The national cricket team wins championship final by five wickets", "Sports"),
    
    # Business
    ("The company reported record quarterly profits and announced expansion plans", "Business"),
    ("The global corporation acquires rival firm in multi-billion dollar merger", "Business"),
    ("The tech giant announces restructuring plan including executive changes", "Business"),
    ("The enterprise software provider signs strategic partnership with retail giant", "Business"),
    ("The company expanded its operations to three new international markets", "Business"),
    ("The CEO announced a new strategic direction focusing on sustainable practices", "Business"),
    ("The small business owners express concern over rising inflation and labor costs", "Business"),
    ("The airline ordered 50 new aircraft in a deal worth 5 billion dollars", "Business"),
    ("The pharmaceutical company receives FDA approval for breakthrough gene therapy", "Business"),
    ("The startup secured 50 million dollars in Series B funding round", "Business"),
    
    # Finance
    ("The central bank raised interest rates by 25 basis points to combat inflation", "Finance"),
    ("Wall Street stock indices surge following positive corporate earnings", "Finance"),
    ("The stock market plunged 500 points on fears of recession", "Finance"),
    ("Gold prices hit a record high amid global economic uncertainty", "Finance"),
    ("The Federal Reserve signaled it may cut interest rates later this year", "Finance"),
    ("The yield on 10-year treasury bonds fell to its lowest level in months", "Finance"),
    ("The finance minister unveiled a new budget with increased infrastructure spending", "Finance"),
    ("The hedge fund reported annual returns of 25 percent for its investors", "Finance"),
    ("The credit rating agency downgraded the nation's sovereign debt rating", "Finance"),
    ("The investment banks adjust portfolio allocations amid shifts in global currency", "Finance"),
    
    # Health
    ("The health ministry issued new guidelines for vaccination and preventive care", "Health"),
    ("A new study found that exercise reduces the risk of heart disease", "Health"),
    ("The hospital opened a new wing dedicated to cancer treatment and research", "Health"),
    ("Public health officials recommend preventive screening for chronic illnesses", "Health"),
    ("The mental health initiative launched to support adolescent well-being", "Health"),
    ("The World Health Organization declared a public health emergency", "Health"),
    ("The new vaccine was approved for the prevention of malaria", "Health"),
    ("The health insurance marketplace opened for annual enrollment", "Health"),
    ("The wellness industry is projected to reach 7 trillion dollars by 2026", "Health"),
    ("The researchers found that meditation can lower blood pressure and reduce stress", "Health"),
    
    # Science
    ("Scientists discovered a new species of deep-sea fish in the Pacific Ocean", "Science"),
    ("The research team published their findings on gene editing in a peer-reviewed journal", "Science"),
    ("Physicists at quantum lab observe new state of matter using ultra-cold atom traps", "Science"),
    ("The genomics research team sequences complete genome of rare marine species", "Science"),
    ("Biologists discover novel enzyme capable of breaking down synthetic plastics", "Science"),
    ("The particle accelerator experiment confirms theoretical predictions", "Science"),
    ("The chemistry team synthesized a new compound with potential pharmaceutical applications", "Science"),
    ("Marine scientists discovered a previously unknown species in the deep ocean trench", "Science"),
    ("The archaeological discovery pushes back the timeline of human migration", "Science"),
    ("Climate scientists published new data on global temperature trends", "Science"),
    
    # Entertainment
    ("The blockbuster movie broke box office records earning over 200 million dollars", "Entertainment"),
    ("The streaming service announced a new original series starring A-list actors", "Entertainment"),
    ("The annual awards show celebrates top achievements in television and streaming", "Entertainment"),
    ("The celebrity couple announces charitable foundation launch during red carpet event", "Entertainment"),
    ("The popular reality TV series renewed for two more seasons", "Entertainment"),
    ("The talk show host announced their retirement after 25 years on air", "Entertainment"),
    ("The Broadway musical won multiple Tony awards including best musical", "Entertainment"),
    ("The film festival awarded the top prize to an independent documentary", "Entertainment"),
    ("The comedy special received rave reviews from critics and audiences", "Entertainment"),
    ("The music festival lineup features headliners from around the world", "Entertainment"),
    
    # Food
    ("The renowned chef opens farm-to-table restaurant featuring seasonal organic produce", "Food"),
    ("The culinary institute publishes guide on plant-based cooking techniques", "Food"),
    ("Food critics praise new bistro for innovative fusion of Mediterranean and Asian flavors", "Food"),
    ("The food delivery app expanded its services to 50 new cities", "Food"),
    ("The food truck festival offered a variety of international street food", "Food"),
    ("The artisanal bakery is known for its sourdough bread and pastries", "Food"),
    ("The cooking show featured celebrity chefs competing in a culinary challenge", "Food"),
    ("The food safety inspection revealed violations at several restaurants", "Food"),
    ("The organic food market saw a surge in demand among health-conscious consumers", "Food"),
    ("The food science researcher developed a new method for preserving freshness", "Food"),
    
    # Automotive
    ("The automaker unveils new electric vehicle with 500-mile battery range", "Automotive"),
    ("The autonomous vehicle company expands self-driving robotaxi fleet testing", "Automotive"),
    ("The sports car brand releases hybrid supercar powered by V8 engine", "Automotive"),
    ("The car manufacturer recalled 100,000 vehicles due to a safety defect", "Automotive"),
    ("The automotive exhibition showcased the latest concept cars and innovations", "Automotive"),
    ("The electric vehicle sales surpassed traditional gasoline cars for the first time", "Automotive"),
    ("The automotive supplier developed a new lightweight material for car bodies", "Automotive"),
    ("The racing team won the championship with their new aerodynamic design", "Automotive"),
    ("The car review magazine named the best model in its class", "Automotive"),
    ("The automotive software update improved the vehicle's performance and safety", "Automotive"),
    
    # Other categories - quick samples
    ("The United Nations Security Council held an emergency session to address the crisis", "World"),
    ("The federal government announces nationwide infrastructure development project", "National"),
    ("The city council approves budget for new community park and library", "Local"),
    ("The GDP grew by 3.5 percent driven by consumer spending and exports", "Economy"),
    ("NASA successfully launched a new satellite to study climate change", "Space"),
    ("The senator proposed a new law to reform healthcare policy", "Politics"),
    ("The central bank raised interest rates to combat inflation", "Finance"),
    ("The Supreme Court ruling establishes landmark legal precedent", "Law"),
    ("Police arrest suspect involved in high-profile bank robbery", "Crime"),
    ("The conservation project restores coastal wetlands protecting endangered species", "Environment"),
    ("The UN climate summit concludes with a new agreement to reduce emissions", "Climate"),
    ("Heavy rainfall and flood warnings issued across the region", "Weather"),
    ("The aviation association reports record summer passenger travel volume", "Travel"),
    ("The historical heritage site sees 30% surge in foreign tourist arrivals", "Tourism"),
    ("Wellness experts share tips on mindfulness and work-life integration", "Lifestyle"),
    ("Paris Fashion Week showcases innovative sustainable fabrics and designs", "Fashion"),
    ("The video game studio releases open-world action RPG with ray tracing", "Gaming"),
    ("The Grammy-winning artist releases surprise studio album", "Music"),
    ("The sci-fi blockbuster breaks box office records", "Movies"),
    ("India wins the final match by five wickets in dramatic thriller", "Sports"),
    ("The education ministry announces revised national curriculum framework", "Education"),
    ("Clinical trial shows promising results for novel immunotherapy", "Medicine"),
    ("The health ministry issues advisory on seasonal influenza outbreak", "Health"),
    ("Engineers implement deep neural network pipeline using PyTorch", "Machine Learning"),
    ("Apple announces a new AI-powered processor for next-generation devices", "Artificial Intelligence"),
    ("The company reported record quarterly revenue growth", "Business"),
    ("The venture capital firm leads 50 million dollar Series B funding round", "Startups"),
    ("Cybersecurity firm discovers zero-day vulnerability in enterprise OS", "Cybersecurity"),
    ("The advocacy group organizes community march promoting civil rights", "Social Issues"),
    ("The defense department signs contract for next-generation fighter jet", "Defence"),
    ("Ambassadors host multilateral summit to negotiate bilateral trade deal", "International Affairs"),
    ("Farmers adopt precision agriculture technology using drone imagery", "Agriculture"),
    ("The commercial real estate market sees high demand for green buildings", "Real Estate"),
    ("The housing market prices stabilize as mortgage rates fluctuate", "Real Estate"),
]

CATEGORY_METADATA = {
    "Politics": {"icon": "Landmark", "color": "#ef4444", "description": "Government, elections, legislation, political campaigns, and governance policy."},
    "World": {"icon": "Globe", "color": "#3b82f6", "description": "Global developments, international summits, geopolitics, and cross-border events."},
    "National": {"icon": "Flag", "color": "#f59e0b", "description": "Domestic national affairs, federal policies, national statistics, and countrywide news."},
    "Local": {"icon": "MapPin", "color": "#10b981", "description": "City council news, local municipal events, neighborhood updates, and town affairs."},
    "Business": {"icon": "Briefcase", "color": "#8b5cf6", "description": "Corporate news, mergers & acquisitions, industry trends, and business leadership."},
    "Finance": {"icon": "DollarSign", "color": "#10b981", "description": "Banking, interest rates, stock markets, investments, and monetary policy."},
    "Economy": {"icon": "TrendingUp", "color": "#06b6d4", "description": "Macroeconomics, GDP growth, inflation, labor markets, trade balances, and fiscal policy."},
    "Technology": {"icon": "Cpu", "color": "#6366f1", "description": "Hardware devices, semiconductors, software engineering, gadgets, and tech sector news."},
    "Artificial Intelligence": {"icon": "Bot", "color": "#ec4899", "description": "LLMs, generative AI, AI ethics, neural networks, computer vision, and AI products."},
    "Machine Learning": {"icon": "Brain", "color": "#a855f7", "description": "ML algorithms, PyTorch/scikit-learn, deep learning, training pipelines, and data science."},
    "Science": {"icon": "Atom", "color": "#14b8a6", "description": "Scientific discoveries, physics, biology, chemistry, genomics, and laboratory research."},
    "Space": {"icon": "Rocket", "color": "#3b82f6", "description": "Astronomy, NASA/ISRO missions, space exploration, telescopes, and lunar rovers."},
    "Health": {"icon": "HeartPulse", "color": "#f43f5e", "description": "Public health, wellness, preventive care, nutrition, mental health, and medical guidelines."},
    "Medicine": {"icon": "Stethoscope", "color": "#0284c7", "description": "Clinical trials, oncology, drug discovery, vaccines, FDA approvals, and surgery."},
    "Education": {"icon": "GraduationCap", "color": "#eab308", "description": "Schools, universities, academic research, curriculum reform, STEM, and scholarships."},
    "Sports": {"icon": "Trophy", "color": "#f97316", "description": "Cricket, football, Olympics, tennis, athletics, tournaments, and championships."},
    "Entertainment": {"icon": "Tv", "color": "#d946ef", "description": "Pop culture, award shows, celebrities, streaming shows, and media industry."},
    "Movies": {"icon": "Film", "color": "#8b5cf6", "description": "Cinema, box office releases, film festivals, film directors, trailers, and Hollywood."},
    "Music": {"icon": "Music", "color": "#ec4899", "description": "Concerts, album releases, streaming music charts, Grammy awards, and musical artists."},
    "Gaming": {"icon": "Gamepad2", "color": "#84cc16", "description": "Video games, esports tournaments, gaming consoles, game studios, and PC gaming."},
    "Crime": {"icon": "ShieldAlert", "color": "#dc2626", "description": "Law enforcement, criminal investigations, arrests, court trials, and security cases."},
    "Law": {"icon": "Scale", "color": "#d97706", "description": "Supreme Court rulings, antitrust lawsuits, legal precedents, legislation, and judiciary."},
    "Environment": {"icon": "Leaf", "color": "#22c55e", "description": "Ecology, wildlife conservation, plastic waste reduction, forests, and nature reserves."},
    "Climate": {"icon": "ThermometerSun", "color": "#ef4444", "description": "Global warming, COP climate summits, carbon emissions, melting glaciers, and green energy."},
    "Weather": {"icon": "CloudRain", "color": "#0284c7", "description": "Hurricanes, rainfall, severe storms, heatwaves, snowfall, and meteorological alerts."},
    "Travel": {"icon": "Plane", "color": "#06b6d4", "description": "Aviation, airlines, flight routes, solo travel, backpacking, and travel tips."},
    "Tourism": {"icon": "Compass", "color": "#f59e0b", "description": "Heritage sites, resorts, tourist destinations, eco-tourism, and hospitality sector."},
    "Lifestyle": {"icon": "Smile", "color": "#f43f5e", "description": "Mindfulness, wellness, home design, personal growth, productivity, and work-life."},
    "Fashion": {"icon": "Shirt", "color": "#ec4899", "description": "Fashion week, luxury apparel, streetwear, runway designs, and sustainable fabrics."},
    "Food": {"icon": "Utensils", "color": "#f97316", "description": "Culinary arts, restaurants, recipes, farm-to-table produce, plant-based diets, and chefs."},
    "Automotive": {"icon": "Car", "color": "#6366f1", "description": "Electric vehicles, autonomous driving, supercars, auto manufacturers, and EV batteries."},
    "Agriculture": {"icon": "Sprout", "color": "#84cc16", "description": "Farming, crop yields, precision agriculture, irrigation, soil health, and agritech."},
    "Real Estate": {"icon": "Building", "color": "#64748b", "description": "Housing markets, commercial property, mortgage rates, urban development, and condos."},
    "Startups": {"icon": "Zap", "color": "#eab308", "description": "Venture capital, Series A funding, startup incubators, founders, tech unicorns, and seed."},
    "Cybersecurity": {"icon": "Lock", "color": "#ef4444", "description": "Ransomware, zero-day flaws, data breaches, vulnerability fixes, and cyber defense."},
    "Social Issues": {"icon": "Users", "color": "#a855f7", "description": "Civil rights, wage equality, community activism, accessibility, and social justice."},
    "Defence": {"icon": "Shield", "color": "#475569", "description": "Armed forces, defense technology, military exercises, navy ships, and radar systems."},
    "International Affairs": {"icon": "Handshake", "color": "#2563eb", "description": "Diplomatic ties, bilateral treaties, foreign policy, embassies, and international law."},
    "Other": {"icon": "HelpCircle", "color": "#94a3b8", "description": "Miscellaneous news topics, community trivia, unclassified notices, and general posts."}
}